### ISSUE TITLE
Unable to change root namespace of application

### ISSUE THREAD

**Issue by svenluijten** [laravel-zero/framework#114]
The default namespace is `App`, but some people might want to change that. Laravel has taught us that all you'd have to do would just be to change the `composer.json`'s `autoload` and/or `autoload-dev` block and you'd be all set (maybe after running `composer dump-autoload`). 

In Laravel Zero, this `App` namespace is hardcoded into the container, which makes it a bit more cumbersome to change it. You'd have to override the container, pass that into the `Application` via `bootstrap/init.php`, etc... 

After looking around, I found that all the hardcoded namespace was used for was to automatically register commands in the `app/Commands` folder. Do we really still need to hardcode it?

https://github.com/laravel-zero/framework/blob/c4d9fb74c370d14f4e00cadbb8530325a346f011/src/Bootstrappers/LoadCommands.php#L95

**Comment by svenluijten** [comment]
Fixed it for now by doing this: 

```php
$container = new class extends LaravelZero\Framework\Container {
    /**
     * @return string
     */
    public function getNamespace(): string
    {
        return 'CustomNamespace';
    }
};

(new LaravelZero\Framework\Application($container))->run();
```

Obviously not ideal though 😕

**Comment by nunomaduro** [comment]
@svenluijten I understand your problem. Didn't have time yet to check it. Sorry.

**Comment by svenluijten** [comment]
No worries! I decided to see how Laravel does it, and it looks like they just parse the contents of `composer.json`: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Application.php#L1178

**Comment by nunomaduro** [comment]
@svenluijten I find that parse the contents of composer.json can be a bit slow and can lead to parsing errors. What do you think about an optional option on the app.php config? Like:

```
return [
    /*
     * Here goes the application name.
     */
    'name' => 'Laravel Zero',

    /*
     * Here goes the application version.
     */
    'version' => '1.0.0',

    /**
     * Some text...
     */
    'namespace' => 'Sven\ForgeCLI',

     ....
```

**Comment by svenluijten** [comment]
Not sure how it could lead to parsing errors? Looks like Laravel does exactly that when "autoloading" their commands: 

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Console/Kernel.php#L196

Would definitely make it a lot easier if the config value was just stored in one location (`composer.json`, in this case) instead of having two of them that need to be the same at all times.

**Comment by nunomaduro** [comment]
@svenluijten You won. This should be good on the version v4.0.15. Please perform a `composer update laravel-zero/framework` and tell me the results.

**Comment by svenluijten** [comment]
Seems to work fine, thanks! 😄

**Comment by ashleyhood** [comment]
This has broken the built phar as you are unable to read the composer.json file inside the phar.
