### ISSUE TITLE
Parsing composer.json file breaks built phar

### ISSUE THREAD

**Issue by ashleyhood** [laravel-zero/framework#124]
laravel-zero/framework v4.0.15 has broken the built phar as you are unable to read the composer.json file inside the phar.

You may want to consider creating a config/helper file when building the phar that has presets.

For example, you could set the ARTISAN_BINARY constant here as well as the application namespace.  Then you only need to check if these exist otherwise set as normal.

**Comment by svenluijten** [comment]
This is probably because of me 😅 #114. I don't really like the idea of _another_ config file because you'd have to keep the 2 settings (in `composer.json` and your proposed config file) in sync.

**Comment by nunomaduro** [comment]
@ashleyhood My bad. I forget a file on my commit. Should be good on the `v4.0.16`. Please perform `composer update laravel-zero/framework`.

**Comment by ashleyhood** [comment]
@nunomaduro Thanks that works now 😄
