### ISSUE TITLE
Commands outside App Namespace are not registered.

### ISSUE THREAD

**Issue by Neoscopia** [laravel-zero/framework#210]
Hi, me again.

I use a modular approach for handling different behaviors on different server.
I registered a Modules namespace at root level, and made a Modules directory inside app/.
My modules system works perfectly, _every modules commands are correctly registered and run as good as the app/Commands commands_, but this is not the problem here.
I decided to move the Modules directory outside the app folder, but the commands are not registered anymore.
I figured out that Laravel register only commands which are located inside the app folder, as the app_path() method is used.

```php
// Illuminate\Foundation\Console\Kernel - Line 214
<?php
foreach ((new Finder)->in($paths)->files() as $command) {
    $command = $namespace.str_replace(
        ['/', '.php'],
        ['\\', ''],
      Str::after($command->getPathname(), app_path().DIRECTORY_SEPARATOR)
                                          // ^ HERE
    );
});
```
As my modules are not located inside ./app but in ./Modules, the Str::after function return the full path of the command file with the App\ namespace before it (which $namespace variable contains). So the next condition which check if the class is subclass of Command fail and therefore, the command is not registered.

As i registered the namespace Modules at root, i find that it works fine by using the base_path() function if the command is located outside the app folder and by passing the $namespace before the path if it's not.
```php
<?php
$command = str_replace(
    ['/', '.php'],
    ['\\', ''],
    Str::startsWith($command->getPathname(), app_path()) ? 
    $namespace . Str::after($command->getPathname(), app_path().DIRECTORY_SEPARATOR) :
    Str::after($command->getPathname(), base_path().DIRECTORY_SEPARATOR)
);
```

As It's not breaking anything, i wonder if it would be useful for other people and if it deserves a PR. 
I don't know if i should post here or in laravel repo.
Let's talk about this.

**Comment by nunomaduro** [comment]
@Neoscopia Why you have closed this? 😊
