### ISSUE TITLE
ARTISAN_BINARY wrongly declared

### ISSUE THREAD

**Issue by obstschale** [laravel-zero/framework#283]
I tried to setup my custom command to run every 5 minute, but my cron job failed because it could not "open the file", with file it meant my laravel zero app.

I symlinked the app in `/usr/local/bin/sc-cli` and the `schedule:run` command executes `/path/to/php sc-cli <command>` but `sc-cli` is not found here.

I traced down the bug to this line [Kernel::62](https://github.com/laravel-zero/framework/blob/stable/src/Kernel.php#L62) and if I use the complete path to the script (and not only the basename) it seems to work.

Is this a bug or is something wrong with my setup?

**Comment by digitalkreativ** [comment]
IMO, it's not a bug. It's about the way cron jobs work. The `/usr/local/bin/` is not included by default in the cronjob `$PATH` (got that from the stackoverflow answers below).

Someone with the same issue on stackoverflow:
https://serverfault.com/questions/672343/symlink-in-crontab-script-not-found

Why do you want to symlink the script, btw? 

Specifying the full path makes more sense when later revisiting the crontab. You know exactly which script is being executed just by reading it. 
It can be a very long line of course depending where you put the script 😄

**Comment by obstschale** [comment]
Yes this helps. Thank you 👍

**Comment by Broutard** [comment]
+1

When I run "php /a/b/c/application schedule:run" (so, from another directory), it use the constant ARTISAN_BINARY defined by `basename($_SERVER['SCRIPT_FILENAME'])` and try to execute my scheduled command as `'/usr/bin/php' 'application' mycommand > '/dev/null' 2>&1`

... but failed with `Could not open input application` 

It work if I remove `basepath()` in https://github.com/laravel-zero/framework/blob/stable/src/Kernel.php#L63

**Comment by nunomaduro** [comment]
@Broutard Can you create a **new** issue with the detail of your problem?
