### ISSUE TITLE
Cannot set command exit code

### ISSUE THREAD

**Issue by jameswmcnab** [laravel-zero/framework#284]
Currently the `handle()` method on the base `Command` class has a `void` return type, but this prevents me from returning an exit code from the command.

If we changed this return type to `?int` it would allow for an exit code to be returned.

https://github.com/laravel-zero/framework/blob/2c3fa84b642a7cd4b7c51462961fb2af755b5f60/src/Commands/Command.php#L35

**Comment by nunomaduro** [comment]
This is important. Thank you @jameswmcnab.

Unfortunately, this is a breaking change. I will fix this only on Laravel Zero 5.7.

**Comment by jameswmcnab** [comment]
Thanks for responding @nunomaduro 

Agreed that 5.7 is a good time to change this 👍

**Comment by nunomaduro** [comment]
@jameswmcnab Just released laravel Zero 5.7. Please create a new application or follow the upgrade guide [laravel-zero.com/#/upgrade?id=upgrading-to-57-from-56](https://laravel-zero.com/#/upgrade?id=upgrading-to-57-from-56).

Test it, and tell me if it fixes your issue.

**Comment by jameswmcnab** [comment]
@nunomaduro Upgraded and it's working great. Thanks very much for your work on this project!
