### ISSUE TITLE
Allow dependency injection in command handle method

### ISSUE THREAD

**Issue by jameswmcnab** [laravel-zero/framework#286]
Laravel itself [allows injecting dependencies](https://github.com/illuminate/console/blob/7613b77246ec69dd7be034074a1f66d394b5db32/Command.php#L179
) into the `handle` method of your commands, and leaves the `handle` method out of the base `Command` class: 

This is lost by default in Laravel Zero because the `Command` class is extended and [a method signature for the handle method set](https://github.com/laravel-zero/framework/blob/2c3fa84b642a7cd4b7c51462961fb2af755b5f60/src/Commands/Command.php#L35). This means adding anything to this method in order to dependency inject makes the method signature incompatible with with parent.

I've gotten around this by extending the base Laravel `Command` class instead, which seems to work fine. 

1. Do we need the extended `Command` class in Laravel Zero at all? The console stub already works well to provide the boilerplate for the command if using the generator.
2. If we do need it can we drop the `handle` method?

**Comment by nunomaduro** [comment]
@jameswmcnab Just released laravel Zero 5.7. Please create a new application or follow the upgrade guide [laravel-zero.com/#/upgrade?id=upgrading-to-57-from-56](https://laravel-zero.com/#/upgrade?id=upgrading-to-57-from-56).

Test it, and tell me if it fixes your issue.

**Comment by jameswmcnab** [comment]
@nunomaduro Upgraded and it's working great. Thanks very much for your work on this project!
