### ISSUE TITLE
Auto-discovery of service providers is blocked

### ISSUE THREAD

**Issue by ColonelKilkenny** [laravel-zero/framework#287]
Might be that I'm doing something incorrectly but with quick glance it looks like Application.php is deliberately blocking the framework from registering service providers automatically. Is there a reason for that and would we be able to get around it somehow?

I'm basically doing some sort of CLI tool which will have "extensions" and it would be nice to get them to register themselves automatically.

https://github.com/laravel-zero/framework/blob/994ca01b0478c8d5185b2154d866d7634b10cae6/src/Application.php#L44-L47

I reckon there is a reason manifest is set to empty array. It looks like Illuminate checks if it is null and doesn't continue with the discovery. I see there has been action on that part of code around https://github.com/laravel-zero/framework/commit/707315b53fb2eb1c2d96246ddb9fa93dc81370f7 but would be nice to hear why it does that and if something could be done for it.

**Comment by nunomaduro** [comment]
Hey @ColonelKilkenny, unfortunately Laravel Zero don't support auto discovery. And there is no plans for it, ATM.
