### ISSUE TITLE
[enhancement] Allow spaces in directory names when building the app

### ISSUE THREAD

**Issue by linuxjuggler** [laravel-zero/framework#309]
Am not sure if this will cause any problems on other platforms, but basically, if the path has a space in the name for example "Github Projects" the build command will fail.

I guess the issue within this line https://github.com/laravel-zero/framework/blob/4bb23e9a5fb4bc29a2db00446cc03ebedd5c18f2/src/Commands/BuildCommand.php#L96

the fix is simple :

```php
sprintf('./box compile --working-dir="%s" --config="%s"', base_path(), base_path('box.json')),
```

all we need to do is to make sure that we enclose the path within a double quotation, also am a fan of using `sprintf` to clean up the strings a bit.

**Comment by ijpatricio** [comment]
Thanks @linuxjuggler for pointing out the solution! 👌
